### ISSUE TITLE
Clarify Management tenant

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-flexy-integration#1]
I needs to be clarified which Cumulocity Management Tenant are we allowed to show.
Details can be requested at my desk

**Comment by ChrScha** [comment]
@kreinhar 
Confirmed by product owner: All public cloud instances can be added to the drop-down list. In the case of the customer instances, we would have to coordinate this with the relevant customers (A1, etc.).

**Comment by kreinhar** [comment]
@yhegen can you implement the missing cloud instances?

**Comment by yhegen** [comment]
May I have a list of all cloud instances which are requested here? And also I need a list of what are the bootstrap credentials for each of those instances.

**Comment by ChrScha** [comment]
I sent a Mail to get the public instances and bootstrap credentials to empower@softwareag.com. 
(Aaron Kreis did not know this.)

**Comment by ChrScha** [comment]
@yhegen 

The bootstrap credentials are the same on all of the instances:

**Bootstrap User:** management/devicebootstrap
**Bootstrap Password:** Fhdt1bb1f
 
**Here's a list of the public instances:**
cumulocity.com
us.cumulocity.com
apj.cumulocity.com
eu-latest.cumulocity.com
emea.cumulocity.com

**Comment by yhegen** [comment]
So do we still need the dropdown menu for selecting the public instances? At least from my point of view, it is not really necessary for the first release right?

**Comment by ChrScha** [comment]
I don't see the need either.

**Comment by kreinhar** [comment]
please leave the dropdown.. it reminds all that there will be a difference somehow
