### ISSUE TITLE
Data Mapping

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-flexy-integration#11]
Extend the Microservice to handle the mapping from data mailbox to c8y

- [x] extend the MS
- [x] document the Mapping

**Comment by yhegen** [comment]
Mapping documentation: https://github.com/SoftwareAG/cumulocity-flexy-integration/blob/dev/docs/mapping.md

**Comment by yhegen** [comment]
Mapping documentation: https://github.com/SoftwareAG/cumulocity-flexy-integration/blob/dev/docs/mapping.md
