### ISSUE TITLE
UI-Changes for Java Agent

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-flexy-integration#14]
we need to make sure that the user can request the installation of the cumulocity agent.

There are two prerequisites installing the Agent

1. the device does have already a cumulocity agent installed
2. the device does not have a cumulocity agent installed

- [ ] We need to have a UI-Solution so that the User can install the Agent for both prerequisite
- [ ] it needs to be defined under which circumstances the Agent needs to be installed --- prerequisite2

**Comment by yhegen** [comment]
New app is deployed on https://devicecert-testtenant.eu-latest.cumulocity.com/ and ready to be reviewed and test @ChrScha .
