### ISSUE TITLE
Define architecture for creating onloading datamailbox jobs.

### ISSUE THREAD

**Issue by yhegen** [SoftwareAG/cumulocity-flexy-integration#17]
We need to define the process of how to schedule the downloading jobs for certain of devices.

Therefore, we need to make sure to store the scheduled jobs configurations. The microservice can get those data and based on that it goes through the list of devices that need to be synchronized.

**Comment by kreinhar** [comment]
From my point of view we should store each "job" as managed object of typ c8y_dataMailboxJob in the tenant for a Single tenant instance.
If we have an ET we store the "job" in each tenant. Additionally we need to store on which timeslot the microservice is running.
