### ISSUE TITLE
Create UI for Migration - Credentials

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-flexy-integration#2]
Create UI to migrate devices

- [x] define UI and implement all credentials for talk2m
- [x] display account info if the connection was successful
- [x] define UI and implement all credentials for datamailbox
- [x] Define a new tab to fetch data points from datamailbox
- [x] define UI and implement all credentials for management tenant relates on #1 and bootstrap credentials can be used
- [x] make sure we can easily collapse the UI to use in future device certificates 
- [x] make sure the application can support Multi-tenancy
- [x] multiple user credential support

**Comment by yhegen** [comment]
![image](https://user-images.githubusercontent.com/45969355/147478905-97b207f5-d96a-4d05-98c1-45be6bea41ad.png)

![image](https://user-images.githubusercontent.com/45969355/147479084-2d3cf340-6f67-4923-81f8-2723723b53e9.png)

![image](https://user-images.githubusercontent.com/45969355/147484083-8416b6d4-fa57-409f-9d61-78bab370bf95.png)

**Comment by yhegen** [comment]
Moved this task back to "In Progress". Because I will add a feature for multiple user credential support.

**Comment by yhegen** [comment]
Accepted by Stefan Ruhmkorf <str@hms-networks.de>
