### ISSUE TITLE
Create UI for Migration - selecting Devices

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-flexy-integration#3]
create a corresponding UI to select one or more devices

- [x] fetch data and create managed object with list of all devices from talk2m
- [x] define and implement a paging mechanism if the result is more than a specific amount of devices
- [x] define and implement a way to display not already migrated devices
- [x] define and implement a progress bar. possibly with the amount of devices shown to the user.

**Comment by yhegen** [comment]
![image](https://user-images.githubusercontent.com/45969355/147490015-3cef2b97-5262-439a-a072-f8f1bd5b66ab.png)

**Comment by yhegen** [comment]
Accepted by Stefan Ruhmkorf <str@hms-networks.de>
