### ISSUE TITLE
Device Registration

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-flexy-integration#5]
We need to make sure that all selected devices are registered and set in status that the user has nothing additional to do

- [x] all chosen devices exists as managed object devices within c8y and have the fragment c8y_isDevice
- [x] each device has the status `waiting for connection` [Link](https://cumulocity.com/guides/users-guide/device-management/#device-registration)
- [x] devices are created within their corresponding pool name if a pool exists
- [x] only one level of hierarchy (Folder) is created for a pool
- [x] make sure all device information are migrated 2 c8y relates on #6

**Comment by yhegen** [comment]
@kreinhar task is on hold until #6 is defined.

**Comment by yhegen** [comment]
## Is device already integrated?
First checking the c8y platform against externalID = ewonId exists.
If not, the user is able to start a registration process via UI.

Assuming a device request for ewonId already exists but was not used by the device yet to get its credentials, should we **keep this one** and just create a new managed object with externalId? Or do we need to **delete the old request** and **create a new one**? I guess deleting is not necessary right?@kreinhar

**Comment by kreinhar** [comment]
deleting is not necessary

**Comment by yhegen** [comment]
Reviewed and accepted by @kreinhar
